"""grocery model made deli_id nullable true

Revision ID: 2b54e13e5026
Revises: 935308c48767
Create Date: 2025-04-24 16:30:05.141784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b54e13e5026'
down_revision = '935308c48767'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groceries', schema=None) as batch_op:
        batch_op.alter_column('deli_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groceries', schema=None) as batch_op:
        batch_op.alter_column('deli_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
